version: '3'
services:
  traefik:
    image: traefik
    command: -c /dev/null --web --docker
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  eureka:
      image: soa_hrsystem/eureka
      labels:
        - "traefik.port=8761"
        - "traefik.backend=eureka"
        - "traefik.frontend.rule=PathPrefixStrip:/eureka"
      depends_on:
        - traefik

  zuul:
    image: soa_hrsystem/zuul
    labels:
      - "traefik.port=8080"
      - "traefik.backend=zuul"
      - "traefik.frontend.rule=PathPrefixStrip:/zuul"
    depends_on:
      - traefik
      - eureka

  gateway:
    image: soa_hrsystem/gateway
    labels:
      - "traefik.enable=false"
    depends_on:
      - traefik
      - eureka
      - zuul

  login:
    image: soa_hrsystem/login
    labels:
      - "traefik.enable=false"
    depends_on:
      - traefik
      - mysql
      - eureka
      - zuul
    links:
      - mysql
      - eureka

  devices:
    image: soa_hrsystem/devices
    labels:
      - "traefik.enable=false"
    depends_on:
      - traefik
      - mysql
      - eureka
    links:
      - mysql
      - eureka

  archive:
    image: soa_hrsystem/archive
    labels:
      - "traefik.enable=false"
    depends_on:
      - traefik
      - mysql
      - eureka
    links:
      - mysql
      - eureka

  vacations:
    image: soa_hrsystem/vacations
    labels:
      - "traefik.enable=false"
    depends_on:
      - traefik
      - mysql
      - eureka
    links:
      - mysql
      - eureka

  mysql:
    image: mysql
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=blabla
    labels:
      - "traefik=enable=false"
    volumes:
       - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: {}
