version: '3'
services:
  traefik:
    image: traefik
    command: -c /dev/null --web --docker
    labels:
      - "traefik.enable=false"
    ports:
      - "81:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  eureka:
      image: soa_hrsystem/eureka
      labels:
        - "traefik.port=8761"
        - "traefik.backend=eureka"
        - "traefik.frontend.rule=PathPrefixStrip:/eureka"
      depends_on:
        - traefik

  devices:
    image: soa_hrsystem/devices
    labels:
      - "traefik.port=8080"
      - "traefik.backend=devices"
      - "traefik.frontend.rule=PathPrefixStrip:/devices"
    depends_on:
      - traefik
      - mysql
      - eureka
    links:
      - mysql

  archive:
    image: soa_hrsystem/archive
    labels:
      - "traefik.port=8080"
      - "traefik.backend=archive"
      - "traefik.frontend.rule=PathPrefixStrip:/archive"
    depends_on:
      - traefik
      - mysql
      - eureka
    links:
      - mysql

  archive:
    image: soa_hrsystem/vacations
    labels:
      - "traefik.port=8080"
      - "traefik.backend=vacations"
      - "traefik.frontend.rule=PathPrefixStrip:/vacations"
    depends_on:
      - traefik
      - mysql
      - eureka
    links:
      - mysql

  mysql:
    image: mysql
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=blabla
    labels:
      - "traefik=enable=false"
    volumes:
       - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: {}